#!/bin/sh
# Copyright (C) 2026 KersteinS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

exec 2>&1
set -e
file_path="/var/run/docker.pid"
if [ ! -e "$file_path" ]; then
  echo "File '$file_path' does not exist. Waiting for it to appear..."
fi
until [ -e "$file_path" ]; do
  sleep 10
done
DFW_START= /usr/bin/dfw
exec chpst -b dfw tail --pid=$(cat $file_path) -f /dev/null
